services:
  - type: web
    name: yi-restaurant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      PYTHON_VERSION: 
        value: "3.11.9"